version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: goalschool-mysql
    restart: always
    environment:
      MYSQL_DATABASE: goalschool
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
