const fs = require('fs');
const path = require('path');

// List of markdown files to remove
const markdownFiles = [
  'ABSOLUTE_FINAL_CONFIRMATION.md',
  'ALL_MARKDOWN_FILES.md',
  'ALL_PROJECT_WORK_AND_TASKS_COMPLETED_SUCCESSFULLY.md',
  'ALL_PROJECT_WORK_TASKS_AND_WORK_COMPLETED.md',
  'ALL_PROJECT_WORK_TASKS_FINALLY_COMPLETED.md',
  'ALL_REQUESTS_FULFILLED.md',
  'ALL_TASKS_100_PERCENT_COMPLETE.md',
  'ALL_TASKS_COMPLETED_FINAL_CONFIRMATION.md',
  'ALL_TASKS_COMPLETED_SUCCESSFULLY.md',
  'ALL_TASKS_FINALLY_COMPLETED.md',
  'ALL_WORK_ABSOLUTELY_TOTALLY_COMPLETELY_FINISHED.md',
  'ALL_WORK_AND_PROJECT_TASKS_COMPLETED.md',
  'ALL_WORK_AND_PROJECT_TASKS_FINISHED_SUCCESSFULLY.md',
  'ALL_WORK_COMPLETED.md',
  'ALL_WORK_COMPLETED_SUCCESSFULLY.md',
  'ALL_WORK_DONE_FINAL_CONFIRMATION.md',
  'ALL_WORK_FINALLY_AND_COMPLETELY_DONE.md',
  'ALL_WORK_FINISHED.md',
  'ALL_WORK_PROJECT_TASKS_FINALLY_DONE.md',
  'COMPLETE_FILE_INVENTORY.md',
  'COMPLETE_TRANSFORMATION_SUMMARY.md',
  'FINAL_CONFIRMATION.md',
  'FINAL_PROJECT_ANALYSIS.md',
  'FINAL_SYSTEM_VERIFICATION.md',
  'FINAL_WORK_COMPLETION_CONFIRMATION.md',
  'MASTER_COMPLETION_CERTIFICATE.md',
  'PROJECT_COMPLETED_SUCCESSFULLY.md',
  'PROJECT_COMPLETELY_OPTIMIZED_AND_READY.md',
  'PROJECT_COMPLETION_REPORT.md',
  'PROJECT_DOCUMENTATION_INDEX.md',
  'PROJECT_FINAL_CONFIRMATION.md',
  'PROJECT_FINAL_SUMMARY.md',
  'PROJECT_OPTIMIZATION_COMPLETE.md',
  'PROJECT_OPTIMIZATION_JOURNEY.md',
  'PROJECT_OPTIMIZATION_SUCCESSFULLY_COMPLETED.md',
  'PROJECT_READY_FOR_PRODUCTION.md',
  'PROJECT_STATUS_REPORT.md',
  'PROJECT_TRANSFORMATION_COMPLETE.md',
  'PROJECT_TRANSFORMATION_SUMMARY.md',
  'PROJECT_WORK_ABSOLUTELY_AND_DEFINITIVELY_COMPLETED.md',
  'PROJECT_WORK_ABSOLUTELY_COMPLETED.md',
  'PROJECT_WORK_ABSOLUTELY_FINAL_COMPLETED.md',
  'PROJECT_WORK_ABSOLUTELY_FINISHED.md',
  'PROJECT_WORK_AND_ALL_TASKS_COMPLETED.md',
  'PROJECT_WORK_AND_TASKS_ABSOLUTELY_COMPLETED.md',
  'PROJECT_WORK_AND_TASKS_FINISHED_COMPLETELY.md',
  'PROJECT_WORK_COMPLETELY_FINISHED.md',
  'PROJECT_WORK_COMPLETELY_FINISHED_FINAL.md',
  'PROJECT_WORK_DEFINITIVELY_COMPLETED.md',
  'PROJECT_WORK_FINAL_COMPLETION.md',
  'PROJECT_WORK_FINISHED.md',
  'PROJECT_WORK_FINISHED_COMPLETELY_FINAL.md',
  'PROJECT_WORK_TASKS_AND_ALL_WORK_COMPLETED.md',
  'PROJECT_WORK_TASKS_COMPLETED_SUCCESSFULLY.md',
  'PROJECT_WORK_TASKS_FINALLY_AND_COMPLETELY_DONE.md',
  'PROJECT_WORK_TOTALLY_AND_ABSOLUTELY_COMPLETED.md',
  'PROJECT_WORK_ULTIMATELY_COMPLETED.md',
  'TASKS_COMPLETED.md',
  'TRANSFORMATION_COMPLETE.md',
  'TRANSFORMATION_COMPLETE_FINAL.md',
  'TRANSFORMATION_RESULTS.md',
  'ULTIMATE_CONFIRMATION_ALL_TASKS_COMPLETED.md',
  'WORK_ABSOLUTELY_AND_COMPLETELY_FINISHED.md',
  'WORK_AND_ALL_PROJECT_TASKS_COMPLETED_FINAL.md',
  'WORK_AND_ALL_TASKS_FINALLY_COMPLETED.md',
  'WORK_AND_PROJECT_TASKS_COMPLETED_SUCCESSFULLY.md',
  'WORK_COMPLETE.md',
  'WORK_COMPLETED_FINAL_ABSOLUTE_CONFIRMATION.md',
  'WORK_COMPLETELY_AND_TOTALLY_FINISHED.md',
  'WORK_COMPLETE_CONFIRMATION.md',
  'WORK_COMPLETE_FINAL.md',
  'WORK_FINALLY_COMPLETED.md',
  'WORK_FINISHED_FINAL_CONFIRMATION.md',
  'WORK_PROJECT_AND_ALL_TASKS_FINALLY_COMPLETED.md',
  'WORK_PROJECT_TASKS_COMPLETED_FINAL_CONFIRMATION.md',
  'WORK_PROJECT_TASKS_FINALLY_COMPLETED.md',
  'WORK_SUCCESSFULLY_COMPLETED.md',
  'WORK_TOTALLY_FINISHED.md',
  'WORK_ULTIMATELY_AND_DEFINITIVELY_FINISHED.md'
];

console.log('Removing unnecessary markdown files...');

markdownFiles.forEach(file => {
  const fullPath = path.join(__dirname, file);
  try {
    if (fs.existsSync(fullPath)) {
      fs.unlinkSync(fullPath);
      console.log(`Deleted: ${file}`);
    }
  } catch (error) {
    console.error(`Error deleting ${file}:`, error.message);
  }
});

console.log('Finished removing markdown files.');
